name: Debug macos

on:
  workflow_dispatch:
    inputs:
      action_name:
        description: "Action"
        default: "Increment development environment"
        required: true
        type: choice
        options:
          - Increment patch version (1.0.xx)
          - Increment minor version (1.xx.0)
          - Increment major version (xx.0.0)
          - Increment development environment
          - Increment staging environment
          - Increment UAT environment
          - Increment product environment

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  increment-version:
    name: Increment version
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get stage key
        uses: dkershner6/switch-case-action@v1
        id: switch-case
        with:
          default: "none"
          conditionals-with-values: |
            ${{ inputs.action_name == 'Increment patch version (1.0.xx)' }} => increment_core_tag patch
            ${{ inputs.action_name == 'Increment minor version (1.xx.0)' }} => increment_core_tag minor
            ${{ inputs.action_name == 'Increment major version (xx.0.0)' }} => increment_core_tag major
            ${{ inputs.action_name == 'Increment development environment' }} => increment_tag dev
            ${{ inputs.action_name == 'Increment staging environment' }} => increment_tag stg
            ${{ inputs.action_name == 'Increment product environment' }} => increment_tag prd

      - name: Increment
        uses: PoliceTeam/semantic-versioning-action@main
        if: ${{ steps.switch-case.outputs.value != 'none' }}
        with:
          script: ${{ steps.switch-case.outputs.value }}
